# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_exam_window(object):
    def setupUi(self, exam_window):
        exam_window.setObjectName("exam_window")
        exam_window.resize(271, 115)
        self.centralwidget = QtWidgets.QWidget(exam_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.start_ex = QtWidgets.QPushButton(self.centralwidget)
        self.start_ex.setObjectName("start_ex")
        self.verticalLayout.addWidget(self.start_ex)
        self.over_ex = QtWidgets.QPushButton(self.centralwidget)
        self.over_ex.setObjectName("over_ex")
        self.verticalLayout.addWidget(self.over_ex)
        exam_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(exam_window)
        QtCore.QMetaObject.connectSlotsByName(exam_window)

    def retranslateUi(self, exam_window):
        _translate = QtCore.QCoreApplication.translate
        exam_window.setWindowTitle(_translate("exam_window", "exam"))
        self.label.setText(_translate("exam_window", "Введите время экзамена"))
        self.start_ex.setText(_translate("exam_window", "Начать экзамен"))
        self.over_ex.setText(_translate("exam_window", "Закончить экзамен"))
